site_name: Markdown Alley
site_url: https://docs.gooddogdevelopment.com
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo

extra:
  analytics:
    provider: google
    property: G-CWQP6SC78V
