site_name: My Tech Docs
site_url: https://docs.gooddogdevelopment.com
theme:
  name: material  # This uses the popular Material theme included in the image
  palette:
    scheme: slate # Dark mode, naturally.
    primary: indigo